services:
  app:       { volumes: !override [ storage_app:/var/www/handyman/storage/app ] }
  horizon:   { volumes: !override [ storage_app:/var/www/handyman/storage/app ] }
  reverb:    { volumes: !override [ storage_app:/var/www/handyman/storage/app ] }
  scheduler: { volumes: !override [ storage_app:/var/www/handyman/storage/app ] }
  artisan:   { volumes: !override [ storage_app:/var/www/handyman/storage/app ] }

  nginx:
    image: handyman-nginx:local
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: nginx
      args:
        COMPOSER_MIRROR: ${COMPOSER_MIRROR:-https://nexus.telecom.tm/repository/composer-proxy/}
        NPM_REGISTRY: ${NPM_REGISTRY:-https://nexus.telecom.tm/repository/npm-proxy/}
    volumes: !override
      - storage_app:/var/www/handyman/storage/app:ro

volumes:
  storage_app: