x-php-build: &php-dev
  volumes:
    - ./:/var/www/laravel 
  restart: "no"  

services:
  php:
    <<: *php-dev

  nginx:
    restart: "no"
    ports: !override
      - 8000:80
    volumes:
      - ./docker/nginx/conf.d/nginx.conf:/etc/nginx/conf.d/default.conf:ro  
      - ./:/var/www/laravel
      
  queue:
    <<: *php-dev
    command: php artisan queue:listen --tries=3 --backoff=5

  reverb:
    <<: *php-dev
    ports:
      - 8080:8080 
      
  scheduler:
    <<: *php-dev    

  artisan:
    <<: *php-dev

  node:                              # NEW: весь сервис
    image: node:22-alpine
    container_name: handyman_node
    working_dir: /var/www/laravel
    command: sh -c "npm ci && npm run dev"
    volumes:
      - ./:/var/www/laravel
      - node_modules:/var/www/laravel/node_modules
    ports:
      - 5173:5173
    restart: "no" 

  sms-gateway:
    ports:
      - 3000:3000
    restart: "no"     

  db:
    restart: "no"
    ports:
      - 3316:3306

  redis:
    restart: "no"
    ports:
      - "6379:6379"
volumes:
  node_modules:                     # NEW      